### ISSUE TITLE
Failure to import PFXs with RSA 4k size or RSASSA-PSS signature algorithm

### ISSUE THREAD

**Issue by okorsky** [glueckkanja-pki/TPMImport#22]
TPMImport works perfectly with keys of size 2048.

However, when trying to import a cert from PFX that has the private key of size 4096, or when the signature algorithm is RSASSA-PSS, it fails with:

Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The requested operation is not supported.

**Comment by bb-froggy** [comment]
Yes, that happens on all Windows machines currently. The TPM itself supports RSA keys of 4096 bits, but the Platform KSP supports only a maximum key size of 2048 bit. This applies to all current Windows versions up to Windows 11. I have heard that this issue is brought to the attention of the Windows OS team, but I do not know about the status.

It is not an issue of TPMImport in any case, but a limitation of the underlying OS. As soon as it is fixed in the Platform KSP in Windows, TPMImport should be able to import those keys.
